asso_func: giou
conf_thres: 0.5122620708221085
delta_t: 3
det_thresh: 0.6
inertia: 0.2
iou_thresh: 0.3
max_age: 30
min_hits: 1
use_cascade: True
#use_ssim: True
#use_vlad: True
use_ssim: False
use_vlad: False
ssim_ratio: 0.1
vlad_ratio: 0.1
use_byte: True
Q_xy_scaling: 0.01
Q_s_scaling: 0.0001
